### ISSUE TITLE
Some python issues 

### ISSUE THREAD

**Issue by tugdualnicolas** [ex0dus-0x/D0xk1t#3]
Hi got a lot of issues and so i cant use it :c 

 The output : 
 
```
┌─[✗]─[root@kali]─[~/D0xk1t]
└──╼ #./start.py
 You are missing dependencies. They will be installed with pip
 Loading...
Requirement already satisfied: python-nmap in /usr/local/lib/python2.7/dist-packages
Collecting python-geoip
Using cached python_geoip-1.2-py27-none-any.whl
Collecting python-geoip-geolite2
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b4a311990>: Failed to establish a new connection: [Errno -2] Nom ou service inconnu',)': /packages/48/9b/ee1e76561be87db77d66f0ad547bdaa057810b5764977f3beb5b1a119d42/python_geoip_geolite2-2015.0303-py2-none-any.whl
Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b4a311f10>: Failed to establish a new connection: [Errno -2] Nom ou service inconnu',)': /packages/48/9b/ee1e76561be87db77d66f0ad547bdaa057810b5764977f3beb5b1a119d42/python_geoip_geolite2-2015.0303-py2-none-any.whl
Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b4a311ed0>: Failed to establish a new connection: [Errno -2] Nom ou service inconnu',)': /packages/48/9b/ee1e76561be87db77d66f0ad547bdaa057810b5764977f3beb5b1a119d42/python_geoip_geolite2-2015.0303-py2-none-any.whl
Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b4a311590>: Failed to establish a new connection: [Errno -2] Nom ou service inconnu',)': /packages/48/9b/ee1e76561be87db77d66f0ad547bdaa057810b5764977f3beb5b1a119d42/python_geoip_geolite2-2015.0303-py2-none-any.whl
 Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b4a311b90>: Failed to establish a new connection: [Errno -2] Nom ou service inconnu',)': /packages/48/9b/ee1e76561be87db77d66f0ad547bdaa057810b5764977f3beb5b1a119d42/python_geoip_geolite2-2015.0303-py2-none-any.whl
Exception:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
wb.build(autobuilding=True)
 File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
 self.requirement_set.prepare_files(self.finder)
 File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
 ignore_dependencies=self.ignore_dependencies))
 File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
  session=self.session, hashes=hashes)
File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
 hashes=hashes
File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
 hashes)
File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 853, in _download_http_url
 stream=True,
File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 488, in get
 return self.request('GET', url, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 386, in request
return super(PipSession, self).request(method, url, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 475, in request
 resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 596, in send
r = adapter.send(request, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
resp = super(CacheControlAdapter, self).send(request, **kw)
 File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/adapters.py", line 487, in send
raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /packages/48/9b/ee1e76561be87db77d66f0ad547bdaa057810b5764977f3beb5b1a119d42/python_geoip_geolite2-2015.0303-py2-none-any.whl (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b4a311b10>: Failed to establish a new connection: [Errno -2] Nom ou service inconnu',))

```

**Comment by ex0dus-0x** [comment]
It seems to be a network error. If not, use `pip install` and install each dependency manually, listed under section __3a__ in the README file.

**Comment by tugdualnicolas** [comment]
It fixed but i got other issues :/

```
----------------------------------------------------------------
NMap is an open-source tool for network exploration and security
auditing. It is used to scan networks and systems
----------------------------------------------------------------
Loading...
I'm sorry, but right now, I'm working on improving features for this. I will push changes as soon as possible, so make sure to update repository.
----------------------------------------------------------------
 [+] NMap Automatic Network/Host Scanner [+]
 By: Alan Cao
----------------------------------------------------------------
Traceback (most recent call last):
  File "autonmap.py", line 14, in <module>
    nm = nmap.PortScanner()
NameError: name 'nmap' is not defined

```
